In [1]:
import graspdataprocessing as gdp
import sys
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path
import re
from tqdm import tqdm

In [2]:
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path
import re
from tqdm import tqdm
# 添加包的路径到 sys.path
sys.path.append('C:\\Users\\Yenoch\\ProjectFiles\\Python_Project\\GraspDataProcessing\\src')
# sys.path.append('D:\\PythonProjects\\GraspDataProcessing\\src')
import graspdataprocessing as gdp
from typing import Dict, Tuple, List


In [3]:
gdp.__version__

'1.3.dev2'

In [3]:
test1 = {"atom": "GdI", 
              "file_dir": "C:\\Users\\Yenoch\\ProjectFiles\\Python_Project", 
            #   "file_dir": "D:\\test\\Gd_cal_data\\odd1as2069as2.cm", 
              "file_name": "oddcv3pCIas5.cm", 
              "level_parameter": "", 
              "this_as": 2, 
              "file_type": "MIX"}

In [4]:
cmfiledata = gdp.GraspFileLoad(test1).data_file_process()

数据加载路径: C:\Users\Yenoch\ProjectFiles\Python_Project
g92mix: G92MIX
title= G92MIX
 nblock = 3,       ncftot =   681900,          nw =  52,            nelec =   31


100%|██████████| 3/3 [00:00<00:00, 164.77it/s]

cycle jblock = 1
 Block no. = 1, 2J+1 = 2, Parity = -1, No. of eigenvalues = 6, No. of CSFs = 110837
cycle jblock = 2
 Block no. = 2, 2J+1 = 4, Parity = -1, No. of eigenvalues = 11, No. of CSFs = 256184
cycle jblock = 3
 Block no. = 3, 2J+1 = 6, Parity = -1, No. of eigenvalues = 8, No. of CSFs = 314879
data file type: mix_coefficient_data

    Energy levels for ...
Rydberg constant is  109737.31568508

---------------------------------------------
 No Pos  J  Parity   Energy Total    Levels
                      (a.u.)         (cm^-1)
---------------------------------------------

  1  1 1/2   +     -9181.6187361        0.00
  2  1 3/2   +     -9180.4694369   252242.02
  3  2 3/2   +     -9175.5271271  1336953.64
  4  3 3/2   +     -9174.6161009  1536900.80
  5  1 5/2   +     -9174.5904416  1542532.36
  6  4 3/2   +     -9174.5054356  1561189.02
  7  2 5/2   +     -9174.3366324  1598237.03
  8  2 1/2   +     -9174.2111852  1625769.50
  9  5 3/2   +     -9174.0574032  1659520.75
 10  3 

In [8]:
cmfiledata

{'index_block_list': [np.int32(1), np.int32(2), np.int32(3)],
 'ncfblk_list': [np.int32(110837), np.int32(256184), np.int32(314879)],
 'block_energy_count_list': [np.int32(6), np.int32(11), np.int32(8)],
 'j_value_location_list': [np.int32(2), np.int32(4), np.int32(6)],
 'parity_list': [np.int32(-1), np.int32(-1), np.int32(-1)],
 'ivec_list': [array([1, 2, 3, 4, 5, 6], dtype=int32),
  array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32),
  array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)],
 'block_energy_list': [np.float64(-8975.02522248982),
  np.float64(-8972.667231250745),
  np.float64(-8971.553734559478)],
 'block_level_energy_list': [array([-206.59351365, -199.18596276, -199.02583664, -198.13593713,
         -197.50627633, -197.33777478]),
  array([-207.80220567, -202.85989587, -201.94886961, -201.83820434,
         -201.39017199, -200.91481754, -200.67395175, -200.46532447,
         -200.18924043, -199.60096257, -199.57534353]),
  array([-203.036707  , -202.78289785, -202

读取的mix_coefficient_list可以使用.shape函数查看维度和长度，shape[0]对应block_energy_count_list的信息，shape[1]对应ncfblk_list的信息，两个对应成功则表示文件读取成功。这个写在data_io.py 中较好，


mix_data_abs_above_threshold函数的返回值改为字典形式，方便后续处理

In [28]:
for i in cmfiledata['mix_coefficient_list']:
    print(i.shape)

(6, 110837)
(11, 256184)
(8, 314879)


In [6]:
mix_data_dim =cmfiledata['mix_coefficient_list'][0].shape[0]

In [7]:
choosen_mix_data = [[]*mix_data_dim]
for i in range(mix_data_dim):
    print(i)
    print(gdp.mix_data_abs_above_threshold(cmfiledata['mix_coefficient_list'][0][i]))
    



0
{(np.int64(0),): np.float64(0.9944214428087865)}
1
{(np.int64(5),): np.float64(0.9614715526391897), (np.int64(2),): np.float64(-0.17306478881026113), (np.int64(1),): np.float64(0.1726481694198421)}
2
{(np.int64(4),): np.float64(0.9587996365133842), (np.int64(2),): np.float64(-0.22221544528834625), (np.int64(1),): np.float64(-0.1421702685235388)}
3
{(np.int64(3),): np.float64(0.9861853505298497), (np.int64(1),): np.float64(-0.1503849675083116)}
4
{(np.int64(2),): np.float64(0.8696752577693718), (np.int64(1),): np.float64(0.3876128371316011), (np.int64(4),): np.float64(0.2586310612702915)}
5
{(np.int64(1),): np.float64(0.8766765179404239), (np.int64(2),): np.float64(-0.3862817565768035), (np.int64(5),): np.float64(-0.23005360059983754), (np.int64(3),): np.float64(0.1302292830955901)}


In [53]:
mix_data_dim

6

In [52]:
choosen_mix_data

[[]]

In [39]:
choosen_mix_data = np.zeros((mix_data_dim, 0))


In [41]:
choosen_mix_data[0]

array([], dtype=float64)

In [18]:
len(cmfiledata['mix_coefficient_list'][2])

8

In [9]:
jjjj = gdp.mix_data_abs_above_threshold(cmfiledata['mix_coefficient_list'][0][0], 0.01)

In [10]:
indices = [idx[0] for idx in jjjj.keys()]

In [14]:
for index in jjjj.items():
    print(f"Index: {index}, Value")

Index: ((np.int64(0),), np.float64(0.9944214428087865)), Value
Index: ((np.int64(5),), np.float64(0.06260821491317489)), Value
Index: ((np.int64(4),), np.float64(0.04792827654572556)), Value
Index: ((np.int64(2),), np.float64(0.03525065398312147)), Value
Index: ((np.int64(1),), np.float64(0.028154303767416337)), Value
Index: ((np.int64(924),), np.float64(-0.014983641539068277)), Value
Index: ((np.int64(926),), np.float64(-0.014960447109736883)), Value
Index: ((np.int64(32248),), np.float64(0.011493856104874377)), Value
Index: ((np.int64(31567),), np.float64(0.010575833667030585)), Value


In [2]:
test1 = {"atom": "GdI", 
              "file_dir": "D:\\test\\Gd_cal_data\\cvas2069as2", 
              "file_name": "Gdcvas2069as2level", 
              "level_parameter": "", 
              "this_as": 2, 
              "cut_off_subshell": "5p", 
              "file_type": "level"}

In [ ]:
from typing import Dict, Tuple, List



In [3]:
afsdf = ['  5s ( 2)  4d-( 4)  4d ( 6)  5p-( 2)  5p ( 4)  6s ( 2)  4f-( 1)  4f ( 6)  5d ( 1)',
'                                                            5/2        2      5/2',
'                                                                        3/2      1-']

In [4]:
gdp.CSF_item_2_dict(afsdf)

['  ', '5s ( 2)', '  ', '4d-( 4)', '  ', '4d ( 6)', '  ', '5p-( 2)', '  ', '5p ( 4)', '  ', '6s ( 2)', '  ', '4f-( 1)', '  ', '4f ( 6)', '  ', '5d ( 1)', '']
5s (2) is fully charged.
4d-(4) is fully charged.
4d (6) is fully charged.
5p-(2) is fully charged.
5p (4) is fully charged.
6s (2) is fully charged.


{'unfully_charged_subshell': {'4f-': 1, '4f ': 6, '5d ': 1},
 'fully_charged_subshell': {'5s ': 2,
  '4d-': 4,
  '4d ': 6,
  '5p-': 2,
  '5p ': 4,
  '6s ': 2},
 'temp_coupled_j': '                                                            5/2        2      5/2',
 'final_coupled_j_parity': '                                                                        3/2      1-',
 'parity': '-',
 'J': '1'}

In [13]:
subshells_charged = re.split(r'(\d*\w[\s|-]\(\s\d*\))', afsdf[0])

In [15]:
subshells_charged = [item for item in subshells_charged if item.strip()]

In [16]:
afsdf[1:]

['                                                            5/2        2      5/2',
 '                                                                        3/2      1-']

In [14]:
def CSFs_subshell_compress(CSFs_configuration_raw: str):
    
    subshells_charged = re.split(r'(\d*\w[\s|-]\(\s\d*\))', CSFs_configuration_raw)
    subshells_charged = [item for item in subshells_charged if item.strip()]
    
    print(subshells_charged)
    compressed_CSFs = ''
    
    for subshell in subshells_charged:
        temp_subshell_charged_state = gdp.subshell_charged_state(subshell)
        temp_subshell_kappa = gdp.str_subshell_2_kappa(temp_subshell_charged_state['subshell_name'])
        compressed_CSFs += f'{temp_subshell_charged_state['subshell_main_quantum_num']}|{temp_subshell_kappa}|{temp_subshell_charged_state['subshell_charged_num']};'

    # for match in re.finditer(pattern, original_str):
    #     n, orbital, value = match.groups()
    #     # 标准化轨道符号格式
    #     orbital = orbital.replace(' ', '').rstrip('-') + ('-' if '-' in orbital else ' ')
    #     if orbital not in kappa_value:
    #         continue
    #     simplified.append(f"{int(n)}|{kappa_value[orbital]}|{value}")
    
    # return ' '.join(simplified)
    return compressed_CSFs

In [15]:
CSFs_subshell_compress(afsdf[0])

['5s ( 2)', '4d-( 4)', '4d ( 6)', '5p-( 2)', '5p ( 4)', '6s ( 2)', '4f-( 1)', '4f ( 6)', '5d ( 1)']


'5|-1|2;4|2|4;4|-3|6;5|1|2;5|-2|4;6|-1|2;4|3|1;4|-4|6;5|-3|1;'

In [19]:
sys.getsizeof('  5s ( 2)  4d-( 4)  4d ( 6)  5p-( 2)  5p ( 4)  6s ( 2)  4f-( 1)  4f ( 6)  5d ( 1)')

122

In [1]:
def read_fortran_record(file, dtype, count=1):
    # Read the record length (4 bytes before the data)
    record_len_before = np.fromfile(file, dtype=np.int32, count=1)[0]
    
    # Print for debugging
    # print(f"Record length before: {record_len_before}")
    
    # Read the actual data
    data = np.fromfile(file, dtype=dtype, count=count)
    
    # Read the record length (4 bytes after the data)
    record_len_after = np.fromfile(file, dtype=np.int32, count=1)[0]
    
    # Print for debugging
    # print(f"Record length after: {record_len_after}")
    
    # Verify that the record lengths match
    if record_len_before != record_len_after:
        raise ValueError(f"Record length mismatch: {record_len_before} != {record_len_after}")
    
    return data

In [22]:
compressed_CSFs = ''
for subshell in subshells_charged:
    temp_subshell_charged_state = gdp.subshell_charged_state(subshell)
    temp_subshell_kappa = gdp.str_subshell_2_kappa(temp_subshell_charged_state['subshell_name'])
    compressed_CSFs += f'{temp_subshell_charged_state['subshell_main_quantum_num']}|{temp_subshell_kappa}|{temp_subshell_charged_state['subshell_charged_num']};'

In [23]:
compressed_CSFs

'5|-1|2;4|2|4;4|-3|6;5|1|2;5|-2|4;6|-1|2;4|3|1;4|-4|6;5|-3|1;'

In [3]:
test3 = {"atom": "GdIoddIcvIItest", 
              "file_dir": "D:\\test\\Gd_cal_data\\cvas2069as2", 
              "file_name": "", 
              "level_parameter": "as2069as", 
              "this_as": 2, 
              "cut_off_subshell": "5p", 
              "file_type": "TRANSITION"}

In [7]:
leveldata = gdp.LevelsASFComposition(leveldata, test3)

load data files from D:\test\Gd_cal_data\cvas2069as2
*as2069as*2.lsj.lbl data file is found
[WindowsPath('D:/test/Gd_cal_data/cvas2069as2/even1as2069as2.lsj.lbl'), WindowsPath('D:/test/Gd_cal_data/cvas2069as2/odd1as2069as2.lsj.lbl')]
file D:\test\Gd_cal_data\cvas2069as2\even1as2069as2.lsj.lbl loaded
file D:\test\Gd_cal_data\cvas2069as2\odd1as2069as2.lsj.lbl loaded
data file type: level jj2lsj data


In [4]:
leveldata = gdp.ci_energy_data_collection(None, test1)

load data files from D:\test\Gd_cal_data\cvas2069as2
file D:\test\Gd_cal_data\cvas2069as2\Gdcvas2069as2level loaded
data file type: level data
energy levels data has been written into D:\test\Gd_cal_data\cvas2069as2\csv_file\Gdcvas2069as2level_level.csv csv file


In [6]:
test2 = {"atom": "GdIoddIcvIItest", 
              "file_dir": "D:\\test\\Gd_cal_data\\cvas2069as2", 
              "file_name": "", 
              "level_parameter": "as2069", 
              "this_as": 2, 
              "cut_off_subshell": "5p", 
              "file_type": "TRANSITION"}

In [7]:
transition_data_collection = gdp.TransitionDataCollection(test2)

data_pd = transition_data_collection.transition_data2dataframe()

load data files from D:\test\Gd_cal_data\cvas2069as2
*.*.*t data file is found
file D:\test\Gd_cal_data\cvas2069as2\odd-even\odd1as2069as2.even1as2069as2.ct loaded
data file type: transition_data
[5, 68, 75, 82, 130]


100%|██████████| 3/3 [00:00<00:00, 43.48it/s]
