In [1]:
import graspdataprocessing as gdp
import sys
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path
import re
from tqdm import tqdm

In [2]:
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pathlib import Path
import re
from tqdm import tqdm
# 添加包的路径到 sys.path
# sys.path.append('C:\\Users\\Yenoch\\ProjectFiles\\Python_Project\\GraspDataProcessing\\src')
sys.path.append('D:\\PythonProjects\\GraspDataProcessing\\src')
import graspdataprocessing as gdp
from typing import Dict, Tuple, List


In [3]:
gdp.__version__

'1.3.dev2'

In [3]:
test1 = {"atom": "GdI", 
              # "file_dir": "C:\\Users\\Yenoch\\ProjectFiles\\Python_Project", 
              "file_dir": "D:\\test\\Gd_cal_data\\even1as2069as2.cm", 
              "file_name": "even1as2069as2.cm", 
              "level_parameter": "", 
              "this_as": 2, 
              "file_type": "MIX"}

In [4]:
cmfiledata = gdp.GraspFileLoad(test1).data_file_process()

数据加载路径: D:\test\Gd_cal_data\even1as2069as2.cm
g92mix: G92MIX
 nblock = 4,       ncftot =   762811,          nw =  32,            nelec =   64


100%|██████████| 4/4 [00:00<00:00, 2000.62it/s]

cycle jblock = 1
 Block no. = 1, 2J+1 = 5, Parity = 1, No. of eigenvalues = 1, No. of CSFs = 153783
cycle jblock = 2
 Block no. = 2, 2J+1 = 7, Parity = 1, No. of eigenvalues = 2, No. of CSFs = 230233
cycle jblock = 3
 Block no. = 3, 2J+1 = 9, Parity = 1, No. of eigenvalues = 1, No. of CSFs = 214863
cycle jblock = 4
 Block no. = 4, 2J+1 = 11, Parity = 1, No. of eigenvalues = 1, No. of CSFs = 163932
data file type: mix_coefficient_data

    Energy levels for ...
Rydberg constant is  109737.31568508

---------------------------------------------
 No Pos  J  Parity   Energy Total    Levels
                      (a.u.)         (cm^-1)
---------------------------------------------

  1  1   3   +    -11257.5731386        0.00
  2  1   4   +    -11257.5713477      393.05
  3  1   5   +    -11257.5625843     2316.39
  4  2   3   +    -11257.5574171     3450.46
  5  1   2   +    -11257.5564260     3667.98


In [7]:
cmfiledata

{'CSFs_blocks_num': np.int32(4),
 'index_block_list': [np.int32(1), np.int32(2), np.int32(3), np.int32(4)],
 'ncfblk_list': [np.int32(153783),
  np.int32(230233),
  np.int32(214863),
  np.int32(163932)],
 'block_energy_count_list': [np.int32(1),
  np.int32(2),
  np.int32(1),
  np.int32(1)],
 'j_value_location_list': [np.int32(5),
  np.int32(7),
  np.int32(9),
  np.int32(11)],
 'parity_list': [np.int32(1), np.int32(1), np.int32(1), np.int32(1)],
 'ivec_list': [array([1], dtype=int32),
  array([1, 2], dtype=int32),
  array([1], dtype=int32),
  array([1], dtype=int32)],
 'block_energy_list': [np.float64(-11253.913478323164),
  np.float64(-11253.7769297429),
  np.float64(-11253.827802866615),
  np.float64(-11253.880095415565)],
 'block_level_energy_list': [array([-3.64294771]),
  array([-3.79620882, -3.78048735]),
  array([-3.74354484]),
  array([-3.68248891])],
 'mix_coefficient_list': [array([[ 4.99379273e-02, -1.14010267e-04, -2.09406775e-04, ...,
           6.67128126e-06, -6.23697973e

In [4]:
if True:
    raise ValueError('''ncfblk: number of configuration functions in block
            len(evals): number of eigenvalues in block
            ncfblk should equal len(evals)''')

ValueError: ncfblk: number of configuration functions in block
            len(evals): number of eigenvalues in block
            ncfblk should equal len(evals)

In [11]:
test = []

In [41]:
test={}
for block in range(cmfiledata['CSFs_blocks_num']):
    block_level_num = len(cmfiledata['mix_coefficient_list'][block])
    for i in range(block_level_num):
        temp_coeff = gdp.mix_data_abs_above_threshold(cmfiledata['mix_coefficient_list'][block][i], threshold=0.1)
        test[f'block{block}_No{i}'] = temp_coeff

In [26]:
for i in cmfiledata['mix_coefficient_list'][1]:
    print(len(i))

230233
230233


In [49]:
test['block1_No1']

{(np.int64(143),): np.float64(0.46799521811299183),
 (np.int64(218),): np.float64(-0.45082542882925836),
 (np.int64(58),): np.float64(0.34667654657971575),
 (np.int64(251),): np.float64(-0.29726417257528676),
 (np.int64(91),): np.float64(0.22759034190289992),
 (np.int64(197),): np.float64(0.197227697320618),
 (np.int64(11),): np.float64(-0.1756043273891065),
 (np.int64(37),): np.float64(-0.15170943633689324),
 (np.int64(118),): np.float64(-0.1397228187540826),
 (np.int64(259),): np.float64(-0.11096479683867527),
 (np.int64(195),): np.float64(0.11054407571911441),
 (np.int64(249),): np.float64(-0.10778944003253012)}

In [37]:
len(cmfiledata['mix_coefficient_list'][0])

1

In [36]:
test={}

In [30]:
test[0].append(gdp.mix_data_abs_above_threshold(cmfiledata['mix_coefficient_list'][0][0], threshold=0.1))


IndexError: list index out of range

In [35]:
for index, value in xc.items():
    print(index[0], value)

118 0.47827471429097684
179 -0.4605669315660445
48 0.35266987808405914
206 -0.3020619763448602
75 0.23025795949417804
162 0.1994962068240619
9 -0.17693831069978205
31 -0.15273121435239093
98 -0.14062955971766924
212 -0.11159761285064403
161 0.110898441078288
205 -0.10786298664462789


In [33]:
xc = gdp.mix_data_abs_above_threshold(cmfiledata['mix_coefficient_list'][0][0], threshold=0.1)

In [18]:
len(cmfiledata['mix_coefficient_list'][0])

1

读取的mix_coefficient_list可以使用.shape函数查看维度和长度，shape[0]对应block_energy_count_list的信息，shape[1]对应ncfblk_list的信息，两个对应成功则表示文件读取成功。这个写在data_io.py 中较好，


mix_data_abs_above_threshold函数的返回值改为字典形式，方便后续处理

In [28]:
for i in cmfiledata['mix_coefficient_list']:
    print(i.shape)

(6, 110837)
(11, 256184)
(8, 314879)


In [28]:
llll = ['-','-','-','-','+','-']

In [29]:
set(llll).pop()

'-'

In [6]:
mix_data_dim =cmfiledata['mix_coefficient_list'][0].shape[0]

In [7]:
choosen_mix_data = [[]*mix_data_dim]
for i in range(mix_data_dim):
    print(i)
    print(gdp.mix_data_abs_above_threshold(cmfiledata['mix_coefficient_list'][0][i]))
    



0
{(np.int64(0),): np.float64(0.9944214428087865)}
1
{(np.int64(5),): np.float64(0.9614715526391897), (np.int64(2),): np.float64(-0.17306478881026113), (np.int64(1),): np.float64(0.1726481694198421)}
2
{(np.int64(4),): np.float64(0.9587996365133842), (np.int64(2),): np.float64(-0.22221544528834625), (np.int64(1),): np.float64(-0.1421702685235388)}
3
{(np.int64(3),): np.float64(0.9861853505298497), (np.int64(1),): np.float64(-0.1503849675083116)}
4
{(np.int64(2),): np.float64(0.8696752577693718), (np.int64(1),): np.float64(0.3876128371316011), (np.int64(4),): np.float64(0.2586310612702915)}
5
{(np.int64(1),): np.float64(0.8766765179404239), (np.int64(2),): np.float64(-0.3862817565768035), (np.int64(5),): np.float64(-0.23005360059983754), (np.int64(3),): np.float64(0.1302292830955901)}


In [2]:
with open('D:\\test\\Gd_cal_data\\even1as2069as2.c', 'r') as file:
    data = file.readlines()

In [3]:
gdp.get_CSFs_file_info(data)

{'raw_subshell_info': ['Core subshells:\n',
  '  1s   2s   2p-  2p   3s   3p-  3p   3d-  3d   4s   4p-  4p\n',
  'Peel subshells:\n',
  '  5s   4d-  4d   5p-  5p   6s   4f-  4f   5d-  5d   6p-  6p   7s   5f-  5f   6d-  6d   7p-  7p   8s\n'],
 'Core subshells:\n': ['1s',
  '2s',
  '2p-',
  '2p',
  '3s',
  '3p-',
  '3p',
  '3d-',
  '3d',
  '4s',
  '4p-',
  '4p'],
 'Peel subshells:\n': ['5s',
  '4d-',
  '4d',
  '5p-',
  '5p',
  '6s',
  '4f-',
  '4f',
  '5d-',
  '5d',
  '6p-',
  '6p',
  '7s',
  '5f-',
  '5f',
  '6d-',
  '6d',
  '7p-',
  '7p',
  '8s'],
 'star_indices': [461354, 1152054, 1796644],
 'CSFs_block_data': [['  5s ( 2)  4d-( 4)  4d ( 6)  5p-( 2)  5p ( 4)  6s ( 2)  4f ( 7)  6p ( 1)\n',
   '                                                            7/2      3/2\n',
   '                                                                        2+\n',
   '  5s ( 2)  4d-( 4)  4d ( 6)  5p-( 2)  5p ( 4)  6s ( 2)  4f-( 1)  4f ( 6)  6p ( 1)\n',
   '                                           

In [53]:
mix_data_dim

6

In [52]:
choosen_mix_data

[[]]

In [39]:
choosen_mix_data = np.zeros((mix_data_dim, 0))


In [41]:
choosen_mix_data[0]

array([], dtype=float64)

In [18]:
len(cmfiledata['mix_coefficient_list'][2])

8

In [9]:
jjjj = gdp.mix_data_abs_above_threshold(cmfiledata['mix_coefficient_list'][0][0], 0.01)

In [10]:
indices = [idx[0] for idx in jjjj.keys()]

In [14]:
for index in jjjj.items():
    print(f"Index: {index}, Value")

Index: ((np.int64(0),), np.float64(0.9944214428087865)), Value
Index: ((np.int64(5),), np.float64(0.06260821491317489)), Value
Index: ((np.int64(4),), np.float64(0.04792827654572556)), Value
Index: ((np.int64(2),), np.float64(0.03525065398312147)), Value
Index: ((np.int64(1),), np.float64(0.028154303767416337)), Value
Index: ((np.int64(924),), np.float64(-0.014983641539068277)), Value
Index: ((np.int64(926),), np.float64(-0.014960447109736883)), Value
Index: ((np.int64(32248),), np.float64(0.011493856104874377)), Value
Index: ((np.int64(31567),), np.float64(0.010575833667030585)), Value


In [2]:
test1 = {"atom": "GdI", 
              "file_dir": "D:\\test\\Gd_cal_data\\cvas2069as2", 
              "file_name": "Gdcvas2069as2level", 
              "level_parameter": "", 
              "this_as": 2, 
              "cut_off_subshell": "5p", 
              "file_type": "level"}

In [ ]:
from typing import Dict, Tuple, List



In [3]:
test3 = {"atom": "GdIoddIcvIItest", 
              "file_dir": "D:\\test\\Gd_cal_data\\cvas2069as2", 
              "file_name": "", 
              "level_parameter": "as2069as", 
              "this_as": 2, 
              "cut_off_subshell": "5p", 
              "file_type": "TRANSITION"}

In [7]:
leveldata = gdp.LevelsASFComposition(leveldata, test3)

load data files from D:\test\Gd_cal_data\cvas2069as2
*as2069as*2.lsj.lbl data file is found
[WindowsPath('D:/test/Gd_cal_data/cvas2069as2/even1as2069as2.lsj.lbl'), WindowsPath('D:/test/Gd_cal_data/cvas2069as2/odd1as2069as2.lsj.lbl')]
file D:\test\Gd_cal_data\cvas2069as2\even1as2069as2.lsj.lbl loaded
file D:\test\Gd_cal_data\cvas2069as2\odd1as2069as2.lsj.lbl loaded
data file type: level jj2lsj data


In [4]:
leveldata = gdp.ci_energy_data_collection(None, test1)

load data files from D:\test\Gd_cal_data\cvas2069as2
file D:\test\Gd_cal_data\cvas2069as2\Gdcvas2069as2level loaded
data file type: level data
energy levels data has been written into D:\test\Gd_cal_data\cvas2069as2\csv_file\Gdcvas2069as2level_level.csv csv file


In [6]:
test2 = {"atom": "GdIoddIcvIItest", 
              "file_dir": "D:\\test\\Gd_cal_data\\cvas2069as2", 
              "file_name": "", 
              "level_parameter": "as2069", 
              "this_as": 2, 
              "cut_off_subshell": "5p", 
              "file_type": "TRANSITION"}

In [7]:
transition_data_collection = gdp.TransitionDataCollection(test2)

data_pd = transition_data_collection.transition_data2dataframe()

load data files from D:\test\Gd_cal_data\cvas2069as2
*.*.*t data file is found
file D:\test\Gd_cal_data\cvas2069as2\odd-even\odd1as2069as2.even1as2069as2.ct loaded
data file type: transition_data
[5, 68, 75, 82, 130]


100%|██████████| 3/3 [00:00<00:00, 43.48it/s]
